from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class Repository(Protocol):
    # settings
    def get_setting(self, key: str) -> Optional[str]: ...
    def set_setting(self, key: str, value: str) -> None: ...
    def hours_per_ects(self) -> int: ...

    # modules
    def add_module(self, data: Dict[str, Any]) -> int: ...
    def update_module(self, module_id: int, **fields: Any) -> None: ...
    def delete_module(self, module_id: int) -> None: ...
    def list_modules(self, status: str = "all") -> List[Any]: ...
    def get_module(self, module_id: int) -> Optional[Any]: ...

    # tasks
    def add_task(self, module_id: int, title: str, priority: str = "Medium",
                 status: str = "Open", due_date: str = "", notes: str = "") -> int: ...
    def update_task(self, task_id: int, **fields: Any) -> None: ...
    def delete_task(self, task_id: int) -> None: ...
    def get_task(self, task_id: int) -> Optional[Any]: ...
    def list_tasks(self, module_id: Optional[int] = None,
                   status: str = "all", priority: str = "all") -> List[Any]: ...

    # events
    def add_event(self, data: Dict[str, Any]) -> int: ...
    def delete_event(self, event_id: int) -> None: ...
    def list_events(self) -> List[Any]: ...

    # time logs
    def add_time_log(self, module_id: int, start_ts: int, end_ts: int, seconds: int,
                     kind: str = "study", note: str = "") -> int: ...
    def list_time_logs(self, module_id: Optional[int] = None, since: Optional[int] = None) -> List[Any]: ...

    # analytics
    def ects_target_hours(self, module_id: int) -> float: ...
    def seconds_studied_for_module(self, module_id: int, since_ts: Optional[int] = None) -> int: ...
    def seconds_studied_week(self, week_start_date) -> int: ...
    def upcoming_exams(self, within_days: int = 30) -> List[Any]: ...
